// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMK06gBJD1MTfv9MR3STB08gBvjVhlQfg',
    appId: '1:80017743006:android:93e9dee55cbc005aecaf8f',
    messagingSenderId: '80017743006',
    projectId: 'taskat-5f982',
    storageBucket: 'taskat-5f982.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNXUemWWrqtksboBgOkKzDPvtscx_-TCQ',
    appId: '1:80017743006:ios:6479861cd6f3faa9ecaf8f',
    messagingSenderId: '80017743006',
    projectId: 'taskat-5f982',
    storageBucket: 'taskat-5f982.firebasestorage.app',
    iosBundleId: 'com.example.taskat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn08i-dkHfFJh_CuALRcTqbi5Gbop8k9Y',
    appId: '1:80017743006:web:962558cf31365637ecaf8f',
    messagingSenderId: '80017743006',
    projectId: 'taskat-5f982',
    authDomain: 'taskat-5f982.firebaseapp.com',
    storageBucket: 'taskat-5f982.firebasestorage.app',
    measurementId: 'G-1XD09WNXDL',
  );

}